name: Forest CI
env:
  MYSQL_DATABASE: pruebaMySQL$test
  MYSQL_USER: pruebaMySQL
  MYSQL_PASSWORD: Ruben_sua00
  MYSQL_HOST: pruebaMySQL.mysql.pythonanywhere-services.com
  NODE_ENV: test
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:19.7.0
    services:
      mysql-master:
        image: mysql:8.0
        ports:
          - 3306/tcp
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        options: >-
          --name=mysql-master
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: "npm ci"
      - name: Setup Database
        run: "npm run"
      - name: Run Tests
        run: |
          "npm i"
          "npm run test"
